package PeticionApp;


/**
* PeticionApp/Peticion.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Peticion.idl
* Saturday, May 8, 2021 7:10:24 PM CEST
*/

public interface Peticion extends PeticionOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Peticion
