package PeticionApp;


/**
* PeticionApp/PeticionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Peticion.idl
* Saturday, May 8, 2021 7:10:24 PM CEST
*/

public interface PeticionOperations 
{
  boolean getFiltrado (String correo, String hash, String nombreImg, String filtro);
} // interface PeticionOperations
