package PeticionApp;


/**
* PeticionApp/PeticionPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Peticion.idl
* Saturday, May 8, 2021 7:10:24 PM CEST
*/

public abstract class PeticionPOA extends org.omg.PortableServer.Servant
 implements PeticionApp.PeticionOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getFiltrado", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // PeticionApp/Peticion/getFiltrado
       {
         String correo = in.read_string ();
         String hash = in.read_string ();
         String nombreImg = in.read_string ();
         String filtro = in.read_string ();
         boolean $result = false;
         $result = this.getFiltrado (correo, hash, nombreImg, filtro);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:PeticionApp/Peticion:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Peticion _this() 
  {
    return PeticionHelper.narrow(
    super._this_object());
  }

  public Peticion _this(org.omg.CORBA.ORB orb) 
  {
    return PeticionHelper.narrow(
    super._this_object(orb));
  }


} // class PeticionPOA
